### ISSUE TITLE
Error in console.

### ISSUE THREAD

**Issue by samata-cdmx** [basvandenberg/ng-select#289]
After upgrading to 1.0.0-rc.4 following error is thrown in console on change on dropdown value 
this.dropdown.hostElement.nativeElement.firstChild.getBoundingClientRect is not a function
    at SelectComponent.updatePosition (ng-select.es5.js:1807)
    at eval (ng-select.es5.js:1634)
    at ZoneDelegate.invokeTask (zone.js:421)
    at Object.onInvokeTask (core.js:4744)
    at ZoneDelegate.invokeTask (zone.js:420)
    at Zone.runTask (zone.js:188)
    at ZoneTask.invokeTask (zone.js:495)
    at ZoneTask.invoke (zone.js:484)
    at timer (zone.js:2065)

**Comment by jasonesteele** [comment]
I see a related error (even on the 1.0.0 branch) when removing dropdown values on a multi-select:

ERROR TypeError: Cannot read property 'hostElement' of undefined
    at SelectComponent.updatePosition (select.component.ts:520)
    at eval (select.component.ts:300)
    at ZoneDelegate.invokeTask (zone.js?1520623047492:424)
    at Object.onInvokeTask (ng_zone.ts:288)
    at ZoneDelegate.invokeTask (zone.js?1520623047492:423)
    at Zone.runTask (zone.js?1520623047492:191)
    at ZoneTask.invoke (zone.js?1520623047492:486)
    at timer (zone.js?1520623047492:1540)
    at ____________________Elapsed_9_ms__At__Fri_Mar_09_2018_14_28_42_GMT_0500__EST_ ()

**Comment by kmsayem** [comment]
core.js:1427 ERROR TypeError: this.dropdown.hostElement.nativeElement.firstChild.getBoundingClientRect is not a function
    at SelectComponent.updatePosition (ng-select.es5.js:1807)
    at eval (ng-select.es5.js:1634)
    at ZoneDelegate.invokeTask (zone.js:425)
    at Object.onInvokeTask (core.js:4744)
    at ZoneDelegate.invokeTask (zone.js:424)
    at Zone.runTask (zone.js:192)
    at ZoneTask.invokeTask (zone.js:499)
    at ZoneTask.invoke (zone.js:488)
    at timer (zone.js:2040)

**Comment by kmsayem** [comment]
same problem -------------- >>>>>>>>>>>>

core.js:1427 ERROR TypeError: this.dropdown.hostElement.nativeElement.firstChild.getBoundingClientRect is not a function
    at SelectComponent.updatePosition (ng-select.es5.js:1807)
    at eval (ng-select.es5.js:1634)
    at ZoneDelegate.invokeTask (zone.js:425)
    at Object.onInvokeTask (core.js:4744)
    at ZoneDelegate.invokeTask (zone.js:424)
    at Zone.runTask (zone.js:192)
    at ZoneTask.invokeTask (zone.js:499)
    at ZoneTask.invoke (zone.js:488)
    at timer (zone.js:2040)

**Comment by basvandenberg** [comment]
Fixed in 1.0.0-rc.5, thanks for reporting.
